# Generated by Django 3.1.6 on 2021-03-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
